esperancanordeste/sale/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

# from esperancanordeste.sale.views import (SaleFormView)
                                          # EstimateFormView)
                                             # ProductCategoryListView,
                                             # ProductDetailListView)


urlpatterns = patterns(
    'esperancanordeste.sale.views',
    url(r'^cotacao/', 'home', name='home'),
    # url(r'^area/', 'home', name='home'),
    # url(r'^orcamento/', 'estimate', name='estimate'),
    # url(r'^area/', SaleFormView.as_view(), name='home'),
    # url(r'^orcamento/', EstimateFormView.as_view(), name='estimate'),
    # url(r'^(?P<category_slug>[-\w]+)/$',
    #     ProductCategoryListView.as_view(),
    #     name='category_list'),
    # url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
    #     ProductDetailListView.as_view(),
    #     name='product_detail'),
)

esperancanordeste/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from esperancanordeste.core.views import (HomeListView, BrandListView)

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'esperancanordeste.core.views.home', name='home'),
    # url(r'^$', HomeListView.as_view(), name='home'),
    url(r'^contato/', 'esperancanordeste.core.views.contact', name='contact'),
    url(r'^institucional/', 'esperancanordeste.core.views.institutional',
        name='institutional'),
    url(r'^pedido/', 'esperancanordeste.core.views.order', name='order'),
    url(r'^marcas/', BrandListView.as_view(), name='brand'),

    url(r'^campanhas/', include('esperancanordeste.campain.urls',
        namespace='campain')),
    url(r'^catalogo/', include('esperancanordeste.catalog.urls',
        namespace='catalog')),
    url(r'^vendas/', include('esperancanordeste.sale.urls',
        namespace='sale')),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # tinymce
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esperancanordeste/sale/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from tinymce import models as tinymce_models

from esperancanordeste.core.models import STATE_CHOICES


OPERATOR_CHOICES = (
    (1, _(u'Fixo')),
    (2, _(u'Claro')),
    (3, _(u'Oi')),
    (4, _(u'Nextel')),
    (5, _(u'Tim')),
    (6, _(u'Vivo')),
    (99, _(u'Outra')),
)


class Area(models.Model):
    description = tinymce_models.HTMLField(_(u'Descrição da página'))

    def admin_description(self):
        return self.description
    admin_description.allow_tags = True
    admin_description.short_description = _(u'Descrição da página')

    def __unicode__(self):
        return unicode(self.description)

    class Meta:
        verbose_name = _(u'Descrição da Página')
        verbose_name_plural = _(u'Descrição da Página')
        ordering = ['-id']


class Segment(models.Model):
    name = models.CharField(_(u'Nome do Segmento'), max_length=50, unique=True)

    def __unicode__(self):
        return unicode(self.name)

    @staticmethod
    def autocomplete_search_fields():
        return ("name__icontains",)

    class Meta:
        verbose_name = _(u'Segmento')
        verbose_name_plural = _(u'Segmentos')
        ordering = ['name']


class SellerAllManager(models.Manager):
    """
    Esse manager carrega todos os objetos do model Entry sem filtros
    """
    def get_queryset(self):
        return super(SellerAllManager,
                     self).get_queryset().all()


class SellerPublishedManager(models.Manager):
    """
    Esse manager carrega todos os objetos do model Entry que estao marcados
    como publish=True
    """
    def get_queryset(self):
        return super(SellerPublishedManager,
                     self).get_queryset().filter(visible=True)


class Seller(models.Model):
    area = models.ForeignKey(Area, verbose_name=_(u'Página'), blank=True,
                             null=True, editable=False)
    name = models.CharField(_(u'Nome'), max_length=150, unique=True)
    state = models.CharField(_(u'UF'), max_length=2, choices=STATE_CHOICES)
    segment = models.ManyToManyField(Segment, verbose_name=_(u'Segmento'))
    visible = models.BooleanField(_(u'Visível no site?'), default=True)

    objects = SellerAllManager()
    published = SellerPublishedManager()

    def get_phone(self):
        out = []
        for k in Phone.objects.filter(seller=self.pk):
            out.append('%s [%s]<br>' % (k.number, k.get_operator_display()))
        return '\n'.join(out)
    get_phone.allow_tags = True
    get_phone.short_description = _(u'Fones')

    def get_email(self):
        out = []
        for k in Email.objects.filter(seller=self.pk):
            out.append('%s<br>' % k.address)
        return '\n'.join(out)
    get_email.allow_tags = True
    get_email.short_description = _(u'Emails')

    def save(self, *args, **kwargs):
        check = Area.objects.all().order_by('-pk')[:1]
        if not check:
            a = Area(description=u"Aguardando conteúdo...")
            a.save()
            self.area = a
        else:
            self.area = check[0]
        super(Seller, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Vendedor')
        verbose_name_plural = _(u'Vendedores')
        ordering = ['name', 'state']


class Phone(models.Model):
    seller = models.ForeignKey('Seller', verbose_name=_(u'Vendedor'))
    operator = models.IntegerField(_(u'Operadora'), choices=OPERATOR_CHOICES)
    number = models.CharField(_(u'Número'), max_length=20,
                              help_text='(99) 9999-9999')
    default = models.BooleanField(_(u'Número principal?'))

    @staticmethod
    def autocomplete_search_fields():
        return ("number__icontains", "operator__icontains",)

    def __unicode__(self):
        return unicode(self.number)

    class Meta:
        verbose_name = _(u'Fone')
        verbose_name_plural = _(u'Fones')
        ordering = ['-default']


class Email(models.Model):
    seller = models.ForeignKey('Seller', verbose_name=_(u'Vendedor'))
    address = models.EmailField(_(u'Endereço de email'))
    default = models.BooleanField(_(u'Email principal?'))

    @staticmethod
    def autocomplete_search_fields():
        return ("address__icontains",)

    def __unicode__(self):
        return unicode(self.address)

    class Meta:
        verbose_name = _(u'Email')
        verbose_name_plural = _(u'Emails')
        ordering = ['-default', 'address']


class Estimate(models.Model):
    created = models.DateTimeField(_(u'Data da Solicitação'),
                                   auto_now_add=True)
    segment = models.ForeignKey('Segment', verbose_name=_(u'Segmento'))
    enterprise = models.CharField(_(u'Empresa'), max_length=200)
    cnpj = models.CharField(_(u'CNPJ'), max_length=20,
                            help_text='99.999.999/9999-99',
                            blank=True, null=True)
    name = models.CharField(_(u'Nome'), max_length=200)
    address = models.CharField(_(u'Endereço'), max_length=200, blank=True,
                               null=True)
    cep = models.CharField(_(u'CEP'), max_length=9, help_text='99999-999',
                           blank=True, null=True)
    complement = models.CharField(_(u'Complemento'), max_length=100,
                                  blank=True, null=True)
    district = models.CharField(_(u'Bairro'), max_length=100,
                                blank=True, null=True)
    city = models.CharField(_(u'Cidade'), max_length=100,
                            blank=True, null=True)
    state = models.CharField(_(u'UF'), max_length=2, choices=STATE_CHOICES,
                             blank=True, null=True)
    phone = models.CharField(_(u'Fone'), max_length=20,
                             help_text='(99) 9999-9999')
    email = models.EmailField(_(u'Email'))
    message = tinymce_models.HTMLField(_(u'Mensagem'))

    def admin_description(self):
        return self.description
    admin_description.allow_tags = True
    admin_description.short_description = _(u'Mensagem')

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Cotação')
        verbose_name_plural = _(u'Cotações')
        ordering = ['-created']

esperancanordeste/sale/forms.py
# coding: utf-8
from django import forms
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives

from esperancanordeste.sale.models import Estimate


class ContactForm(forms.Form):
    email_to = forms.CharField(label=u'Para',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Para',
                                          }),
                               required=False)
    name = forms.CharField(label=u'Nome',
                           widget=forms.TextInput(
                               attrs={'class': 'form-control',
                                      'placeholder': 'Nome'}))
    phone = forms.CharField(label=u'Fone',
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Fone'}))
    email = forms.EmailField(label=u'E-mail',
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'E-mail'}))
    subject = forms.CharField(label=u'Assunto',
                              widget=forms.TextInput(
                                  attrs={'class': 'form-control',
                                         'placeholder': 'Assunto'}))
    message = forms.CharField(label=u'Mensagem',
                              widget=forms.Textarea(
                                  attrs={'class': 'form-control', 'rows': 3,
                                         'placeholder': 'Mensagem'}))

    def send_mail(self):
        subject = u'Contato do site (%s)' % self.cleaned_data['name']
        context = {
            'email_to': self.cleaned_data['email_to'],
            'name': self.cleaned_data['name'],
            'phone': self.cleaned_data['phone'],
            'email': self.cleaned_data['email'],
            'subject': self.cleaned_data['subject'],
            'message': self.cleaned_data['message'],
        }

        email_to = self.cleaned_data['email_to']
        message = render_to_string('contact_mail.txt', context)
        message_html = render_to_string('contact_mail.html', context)
        msg = EmailMultiAlternatives(subject, message,
                                     'no-reply@esperancanordeste.com.br',
                                     ['sac@esperancanordeste.com.br',
                                      email_to])
                                     # ['kleberss@gmail.com'])

        msg.attach_alternative(message_html, 'text/html')
        msg.send()


class EstimateForm(forms.ModelForm):
    email_to = forms.CharField(label=u'Para',
                               widget=forms.TextInput(
                                   attrs={'class': 'form-control',
                                          'placeholder': 'Para',
                                          }),
                               required=False)

    class Meta:
        model = Estimate

    def send_mail(self):
        subject = u'Solicitação de Cotação \
            (%s)' % self.cleaned_data['enterprise']
        context = {
            'email_to': self.cleaned_data['email_to'],
            'segment': self.cleaned_data['segment'],
            'enterprise': self.cleaned_data['enterprise'],
            'cnpj': self.cleaned_data['cnpj'],
            'name': self.cleaned_data['name'],
            'address': self.cleaned_data['address'],
            'cep': self.cleaned_data['cep'],
            'complement': self.cleaned_data['complement'],
            'district': self.cleaned_data['district'],
            'city': self.cleaned_data['city'],
            'state': self.cleaned_data['state'],
            'phone': self.cleaned_data['phone'],
            'email': self.cleaned_data['email'],
            'message': self.cleaned_data['message'],
        }

        email_to = self.cleaned_data['email_to']
        message = render_to_string('sale/estimate_mail.txt', context)
        message_html = render_to_string('sale/estimate_mail.html', context)
        msg = EmailMultiAlternatives(subject, message,
                                     'no-reply@esperancanordeste.com.br',
                                     ['sac@esperancanordeste.com.br',
                                      email_to])

        msg.attach_alternative(message_html, 'text/html')
        msg.send()

esperancanordeste/sale/templates/sale/estimate_mail.html
<p>Solicitação de orçamento enviada pelo site.</p>
<br>
<p><strong>Para:</strong> {{ email_to }}</p>
<p><strong>Segmento:</strong> {{ segment }}</p>
<p><strong>Empresa:</strong> {{ enterprise }}</p>
<p><strong>CNPJ:</strong> {{ cnpj }}</p>
<p><strong>Nome:</strong> {{ name }}</p>
<p><strong>Endereço:</strong> {{ address }}</p>
<p><strong>Complemento:</strong> {{ complement }}</p>
<p><strong>Bairro:</strong> {{ district }}</p>
<p><strong>Cidade:</strong> {{ city }}</p>
<p><strong>Estado:</strong> {{ state }}</p>
<p><strong>Fone:</strong> {{ phone }}</p>
<p><strong>E-mail:</strong> {{ email }}</p>
<p><strong>Mensagem:</strong></p>
{{ message|linebreaks }}

esperancanordeste/sale/templates/sale/sale_estimate.html
{% extends "base.html" %}

{% block nav_estimate %} active{% endblock %}

{% block content %}

    <!-- Wrapper -->
    <div class="wrapper">

      <!-- Topic Header -->
      <div class="topic sale">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <h3>Orçamento</h3>
            </div>
            <!--
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                <li><a href="index.html">Home</a></li>
                <li class="active">Contact Us</li>
              </ol>
            </div>
            -->
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-sm-8">
            <h3 class="headline first-child"><span>Solicite um orçamento</span></h3>
            <p>Pensando sempre no melhor para nossos clientes, criamos essa área especial
            onde você pode solicitar um orçamento direto com nossos vendedores.<br>
            Preencha o formulário abaixo.</p>

            {% if estimate_success %}
            <p>Mensagem enviada com sucesso.</p>
            <a href="{% url 'sale:estimate' %}" class="btn btn-blue">Voltar</a>
            {% else %}
            <form method="post" action=".">
                {% csrf_token %}
                {% for field in estimate_form %}
                    <div class="form-group {% if not field.name = 'message' %}col-sm-6{% else %}col-sm-12{% endif %}">
                        <label for="{{ field.name }}">{{ field.label }}</label>
                        {{ field }}
                        {{ field.errors }}
                    </div>
                {% endfor %}
                <div class="col-sm-12">
                  <input type="submit" name="enviar" class="btn btn-blue" value="Enviar formulário">
                </div>
            </form>
            {% endif %}
          </div>
          <div class="col-sm-4">
            <h3 class="headline second-child"><span>Nosso endereço</span></h3>
            <p>
              {{ enterprise.address }}, {{ enterprise.number }}<br />
              CEP {{ enterprise.cep }}, {{ enterprise.district }}, {{ enterprise.city }}/{{ enterprise.state }} <br />
              Fone: {{ enterprise.phone1 }}<br />
              Email: {{ enterprise.email }}
            </p>
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->

    </div> <!-- / .wrapper -->

{% endblock content %}

{% block extra_js %}

  <script>
    $(document).ready(function(){
        $("input[type=text]").addClass("form-control");
        $("input[type=email]").addClass("form-control");
        $("textarea").addClass("form-control");
        $("select").addClass("form-control");
    });
  </script>

{% endblock extra_js %}

esperancanordeste/sale/templates/sale/sale_home.html
{% extends "base.html" %}

{% block nav_estimate %} active{% endblock %}

{% block content %}

    <!-- Wrapper -->
    <div class="wrapper">

      <!-- Topic Header -->
      <div class="topic sale">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <h3>Área de Atuação
              <small>
                {% if segment or state %}busca por
                {% if segment %} "{{ segment }}"{% endif %}
                {% if state and segment %} em{% endif %}
                {% if state %} "{{ state }}"{% endif %}
                {% endif %}
              </small></h3>
            </div>
            <!--
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                <li><a href="index.html">Home</a></li>
                <li class="active">Contact Us</li>
              </ol>
            </div>
            -->
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            {% for a in area_list %}
            {% autoescape off %}
            <p>{{ a.description|linebreaks|cut:"../../../.." }}<br><br></p>
            {% endautoescape %}
            {% endfor %}
            <h3 class="headline first-child"><span>Encontre o seu vendedor</span></h3>
            <!-- Search -->
            <form role="form" action="." method="get">
              <div class="well">
                <div class="row">
                  <div class="col-sm-12">
                    <div class="input-group">
                      <fieldset class="col-sm-6">
                        <select id="segment" name="segment" class="form-control">
                          <option value="" disabled selected>Segmento</option>
                          {% for seg in segment_list %}
                          <option value="{{ seg.name }}" {% if segment == seg.name %}selected{% endif %}>{{ seg.name }}</option>
                          {% endfor %}
                        </select>
                      </fieldset>
                      <fieldset class="col-sm-6">
                        <select id="state" name="state" class="form-control">
                          <option value="" disabled selected>Estado</option>
                          {% for sta in state_list %}
                          <option value="{{ sta.0 }}" {% if state == sta.0 %}selected{% endif %}>{{ sta.1 }}</option>
                          {% endfor %}
                        </select>
                      </fieldset>
                      <span class="input-group-btn">
                        <button class="btn btn-blue" type="submit"><i class="fa fa-search"></i></button>
                      </span>
                    </div><!-- /input-group -->
                  </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
              </div>
            </form>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-5">
            <h3 class="headline first-child"><span>Selecione um vendedor</span></h3>
            <div class="row new-visitor">
              <label class="col-sm-12 select_email_to">
                <input class="col-sm-1" id="{{ s.pk }}" name="signal_email_to" type="radio">
                <div class="well col-sm-11">
                  <div class="row">
                    <span class="col-sm-12">
                      <p><strong>É novo por aqui?<br>
                      Clique aqui e preencha o formulário ao lado e<br>
                      logo entraremos em contato com você.</strong></p>
                    </span>
                  </div>
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Nome:</strong>
                    </span>
                    <span class="col-sm-10">
                      {{ enterprise.name }}
                    </span>
                  </div>
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Email:</strong>
                    </span>
                    <span class="col-sm-10 email_to">
                      {% autoescape off %}
                      {{ enterprise.email }}
                      {% endautoescape %}
                    </span>
                  </div>
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Fone:</strong>
                    </span>
                    <span class="col-sm-10">
                      {% autoescape off %}
                      {{ enterprise.phone1 }}
                      {% endautoescape %}
                    </span>
                  </div>
                </div>
              </label>
            </div> <!-- . row -->
            {% for s in page_obj %}
            <div class="row">
              <label class="col-sm-12 select_email_to">
                <input class="col-sm-1" id="{{ s.pk }}" name="signal_email_to" type="radio">
                <div class="well col-sm-11">
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Nome:</strong>
                    </span>
                    <span class="col-sm-10">
                      {{ s.name }}
                    </span>
                  </div>
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Email:</strong>
                    </span>
                    <span class="col-sm-10 email_to">
                      {% autoescape off %}
                      {{ s.get_email }}
                      {% endautoescape %}
                    </span>
                  </div>
                  <div class="row">
                    <span class="col-sm-2">
                      <strong>Fone:</strong>
                    </span>
                    <span class="col-sm-10">
                      {% autoescape off %}
                      {{ s.get_phone }}
                      {% endautoescape %}
                    </span>
                  </div>
                </div>
              </label>
            </div> <!-- . row -->
            {% endfor %}

            <center>
              {% include "paginator.html" %}
            </center>

          </div>
          <div class="col-sm-7">
            <h3 class="headline second-child"><span>Solicite um orçamento</span></h3>
            {% if estimate_success %}
            <p>Mensagem enviada com sucesso.</p>
            <a href="{% url 'sale:home' %}" class="btn btn-blue">Voltar</a>
            {% else %}
            <form method="post" action=".">
              {% csrf_token %}
                  <div class="form-group col-sm-12">
                    <label for="email_to">Para</label>
                    <input class="form-control" id="id_email_to" name="email_to" placeholder="Para" type="email" readonly="True">
                  </div>
              {% for field in estimate_form %}
                {% if not field.name = 'email_to' %}
                  <div class="form-group {% if not field.name = 'message' %}col-sm-6{% else %}col-sm-12{% endif %}">
                    <label for="{{ field.name }}">{{ field.label }}</label>
                    {{ field }}
                    {{ field.errors }}
                  </div>
                {% endif %}
              {% endfor %}
              <input type="hidden" name="estimate" value="estimate">
              <div class="form-group col-sm-12">
                <input name="Estimate" type="submit" class="btn btn-blue" value="Enviar mensagem">
              </div>
            </form>
            {% endif %}
          </div>
        </div> <!-- / .row -->

      </div> <!-- / .container -->

    </div> <!-- / .wrapper -->

{% endblock content %}

{% block extra_js %}

  <script>
    $(document).ready(function(){
        $(".select_email_to").click(function(){
            //var email_to=$(this).attr('href').split('=')[1]
            var email_to=$(this).find('.email_to').text().trim();
            email_to=email_to.replace(/\s+/g, ', ');
            $('#id_email_to').val( email_to );
            return true;
        });
    });
    $(document).ready(function(){
        $("input[type=text]").addClass("form-control");
        $("input[type=email]").addClass("form-control");
        $("textarea").addClass("form-control");
        $("select").addClass("form-control");
    });
  </script>

{% endblock extra_js %}