esperancanordeste/campain/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

from esperancanordeste.campain.views import (EntryListView, EntryTagListView,
                                             EntryDetailListView)


urlpatterns = patterns(
    'esperancanordeste.campain.views',
    url(r'^$', EntryListView.as_view(), name='home'),
    url(r'^(?P<slug>[-\w]+)/$', EntryDetailListView.as_view(),
        name='entry_detail'),
    url(r'^categoria/(?P<cat_slug>[-\w]+)/$', EntryTagListView.as_view(),
        name='cat_list'),
)

esperancanordeste/catalog/urls.py
# coding: utf-8
from django.conf.urls import patterns, url

from esperancanordeste.catalog.views import (ProductListView,
                                             ProductCategoryListView,
                                             ProductDetailListView)


urlpatterns = patterns(
    'esperancanordeste.catalog.views',
    url(r'^$', ProductListView.as_view(), name='home'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        ProductCategoryListView.as_view(),
        name='category_list'),
    url(r'^(?P<category_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        ProductDetailListView.as_view(),
        name='product_detail'),
)

esperancanordeste/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static

from esperancanordeste.core.views import (HomeListView, BrandListView)

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', 'esperancanordeste.core.views.home', name='home'),
    # url(r'^$', HomeListView.as_view(), name='home'),
    url(r'^contato/', 'esperancanordeste.core.views.contact', name='contact'),
    url(r'^institucional/', 'esperancanordeste.core.views.institutional',
        name='institutional'),
    url(r'^pedido/', 'esperancanordeste.core.views.order', name='order'),
    url(r'^marcas/', BrandListView.as_view(), name='brand'),

    url(r'^campanhas/', include('esperancanordeste.campain.urls',
        namespace='campain')),
    url(r'^catalogo/', include('esperancanordeste.catalog.urls',
        namespace='catalog')),
    url(r'^vendas/', include('esperancanordeste.sale.urls',
        namespace='sale')),

    url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),

    # tinymce
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^mce_filebrowser/', include('mce_filebrowser.urls')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

esperancanordeste/core/models.py
# coding: utf-8
from django.db import models
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.template.defaultfilters import slugify

from sorl.thumbnail import ImageField
from tinymce import models as tinymce_models

import datetime
now = datetime.datetime.now()

try:
    from PIL import Image, ImageOps
except ImportError:
    import Image
    import ImageOps

from esperancanordeste.catalog.models import Category


STATE_CHOICES = (
    ('AC', u'Acre'),
    ('AL', u'Alagoas'),
    ('AP', u'Amapá'),
    ('AM', u'Amazonas'),
    ('BA', u'Bahia'),
    ('CE', u'Ceará'),
    ('DF', u'Distrito Federal'),
    ('ES', u'Espírito Santo'),
    ('GO', u'Goiás'),
    ('MA', u'Maranhão'),
    ('MT', u'Mato Grosso'),
    ('MS', u'Mato Grosso do Sul'),
    ('MG', u'Minas Gerais'),
    ('PA', u'Pará'),
    ('PB', u'Paraíba'),
    ('PR', u'Paraná'),
    ('PE', u'Pernambuco'),
    ('PI', u'Piauí'),
    ('RJ', u'Rio de Janeiro'),
    ('RN', u'Rio Grande do Norte'),
    ('RS', u'Rio Grande do Sul'),
    ('RO', u'Rondônia'),
    ('RR', u'Roraima'),
    ('SC', u'Santa Catarina'),
    ('SP', u'São Paulo'),
    ('SE', u'Sergipe'),
    ('TO', u'Tocantins'),
)

ICON_CHOICES = (
    ('fa-truck', _(u'Caminhão')),
    ('fa-download', _(u'Baixar')),
    ('fa-edit', _(u'Orçamento')),
)

PAGE_CHOICES = (
    ('pedido', _(u'Pedido')),
    ('orcamento', _(u'Orçamento')),
)


class Social(models.Model):
    description = models.CharField(_(u'Descrição'), max_length=120,
                                   help_text='Breve texto para a área social')

    def __unicode__(self):
        return unicode(self.description)

    class Meta:
        verbose_name = _(u'Social')
        verbose_name_plural = _(u'Social')
        ordering = ['description']


class SocialLogo(models.Model):
    social = models.ForeignKey('Social', verbose_name=_(u'Social'))
    name = models.CharField(_(u'Nome'), max_length=50,
                            help_text='Nome da Instituição')
    image = models.ImageField(_(u'Logo'), upload_to='social',
                              help_text='Tamanho Ideal 115x100 px')
    link = models.URLField(_(u'Site'), blank=True, null=True,
                           help_text='Ex: http://www.instituicao.com.br/')

    def admin_image(self):
        return '<img src="%s" width="115" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Logo da Instituição'

    def save(self, *args, **kwargs):
        if not self.id and not self.image:
            return

        super(SocialLogo, self).save(*args, **kwargs)

        image = Image.open(self.image)
        (width, height) = image.size

        # if (100 / width < 100 / height):
        #     factor = 100 / height
        # else:
        #     factor = 100 / width

        # size = (width / factor, height / factor)
        size = (115, 100)
        """ redimensiona esticando """
        # image = image.resize(size, Image.ANTIALIAS)
        """ redimensiona proporcionalmente """
        # image.thumbnail(size, Image.ANTIALIAS)
        """ redimensiona cortando para encaixar no tamanho """
        image = ImageOps.fit(image, size, Image.ANTIALIAS)
        image.save(self.image.path, 'JPEG', quality=99)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Social Logo')
        verbose_name_plural = _(u'Social Logos')
        ordering = ['name']


class Enterprise(models.Model):
    name = models.CharField(_(u'Nome'), max_length=100)
    description = models.CharField(_(u'Descrição'), max_length=100,
                                   blank=True, null=True)
    cnpj = models.CharField(_(u'CNPJ'), max_length=20,
                            help_text='99.999.999/9999-99')
    address = models.CharField(_(u'Endereço'), max_length=200)
    number = models.CharField(_(u'Número'), max_length=10)
    complement = models.CharField(_(u'Complemento'), max_length=100,
                                  blank=True, null=True)
    cep = models.CharField(_(u'CEP'), max_length=9, help_text='99999-999',
                           blank=True, null=True)
    district = models.CharField(_(u'Bairro'), max_length=100)
    city = models.CharField(_(u'Cidade'), max_length=100)
    state = models.CharField(_(u'UF'), max_length=2, choices=STATE_CHOICES)
    country = models.CharField(_(u'País'), max_length=50)
    phone1 = models.CharField(_(u'Fone 1 (Televendas)'), max_length=20,
                              help_text='(99) 9999-9999')
    phone2 = models.CharField(_(u'Fone 2'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    phone3 = models.CharField(_(u'Fone 3 (Fax)'), max_length=20,
                              help_text='(99) 9999-9999', blank=True,
                              null=True)
    email = models.EmailField(_(u'Email'))
    site = models.URLField(_(u'Site'))

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Empresa')
        verbose_name_plural = _(u'Empresa')


class Order(models.Model):
    body = tinymce_models.HTMLField(_(u'Informações'))

    def admin_body(self):
        return self.body
    admin_body.allow_tags = True
    admin_body.short_description = _(u'Informações')

    def __unicode__(self):
        return unicode(self.body)

    class Meta:
        verbose_name = _(u'Receba seu Pedido')
        verbose_name_plural = _(u'Receba seu Pedido')


class Step(models.Model):
    title = models.CharField(_(u'Título'), max_length=21)
    description = models.CharField(_(u'Descrição'), max_length=90)
    page = models.CharField(_(u'Página'), max_length=20, choices=PAGE_CHOICES,
                            blank=True, null=True, editable=False)
    link = models.URLField(_(u'Link para site externo'), blank=True, null=True,
                           editable=False)

    def __unicode__(self):
        return unicode(self.title)

    class Meta:
        verbose_name = _(u'Caixa da Home')
        verbose_name_plural = _(u'Caixas da Home')


class Institutional(models.Model):
    description = tinymce_models.HTMLField(_(u'Descrição da página'))

    def admin_description(self):
        return self.description
    admin_description.allow_tags = True
    admin_description.short_description = _(u'Descrição da página')

    def __unicode__(self):
        return unicode(self.description)

    class Meta:
        verbose_name = _(u'Institucional')
        verbose_name_plural = _(u'Institucional')


class Timeline(models.Model):
    institutional = models.ForeignKey('Institutional',
                                      verbose_name=_(u'Institucional'))
    title = models.CharField(_(u'Título'), max_length=50)
    description = models.TextField(_(u'Descrição'),
                                   help_text='Uma breve história')
    image = ImageField(_(u'Imagem'), upload_to='institutional/timeline',
                       blank=True, null=True)
    period = models.CharField(_(u'Ano'), max_length=4, unique=True,
                              help_text=now.year)

    def admin_image(self):
        return '<img src="%s" width="200" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Imagem'

    def __unicode__(self):
        return "%s (%s)" % (unicode(self.title), self.period)

    class Meta:
        verbose_name = _(u'Linha do Tempo')
        verbose_name_plural = _(u'Linha do Tempo')
        ordering = ['period']


class PhotoInstitutional(models.Model):
    institutional = models.ForeignKey('Institutional',
                                      verbose_name=_(u'Institucional'))
    title = models.CharField(_(u'Título da Imagem'), max_length=50)
    description = models.CharField(_(u'Descrição'), max_length=200,
                                   blank=True, null=True)
    image = ImageField(_(u'Imagem'), upload_to='institutional/photos')

    def admin_image(self):
        return '<img src="%s" width="160" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Imagem'

    def __unicode__(self):
        return unicode(self.title)

    class Meta:
        verbose_name = _(u'Foto')
        verbose_name_plural = _(u'Fotos')


class Brand(models.Model):
    page = models.CharField(_(u'Nome da página'), max_length=20,
                            default='Marcas', editable=False)
    description = tinymce_models.HTMLField(_(u'Descrição da página'))

    def admin_description(self):
        return self.description
    admin_description.allow_tags = True
    admin_description.short_description = _(u'Descrição da página')

    def __unicode__(self):
        return unicode(self.page)

    class Meta:
        verbose_name = _(u'Marca')
        verbose_name_plural = _(u'Marcas')


class Partner(models.Model):
    brand = models.ForeignKey('Brand', verbose_name=_(u'Página'), default=1,
                              blank=True, null=True)
    name = models.CharField(_(u'Nome'), max_length=30)
    image = ImageField(_(u'Imagem'), upload_to='brand')
    category = models.ManyToManyField(Category, verbose_name='Categorias')

    def admin_image(self):
        return '<img src="%s" width="200" />' % self.image.url
    admin_image.allow_tags = True
    admin_image.short_description = 'Imagem'

    def save(self, *args, **kwargs):
        check = Brand.objects.all()[:1]
        if not check:
            b = Brand(description=u"Aguardando conteúdo...")
            b.save()
            self.brand = b
        super(Partner, self).save(*args, **kwargs)

    def __unicode__(self):
        return unicode(self.name)

    class Meta:
        verbose_name = _(u'Parceiro')
        verbose_name_plural = _(u'Parceiros')


class BannerAllManager(models.Manager):
    """
    Esse manager carrega todos os objetos do model Catalog sem filtros
    """
    def get_queryset(self):

esperancanordeste/core/forms.py
# coding: utf-8
from django import forms
from django.template.loader import render_to_string
from django.core.mail import EmailMultiAlternatives
from django.utils.translation import ugettext_lazy as _

import datetime
now = datetime.datetime.now()

from esperancanordeste.fields import MonthYearWidget
from esperancanordeste.core.models import Timeline


SUBJECT_CHOICES = (
    (_(u'--- Escolha um assunto ---'), _(u'--- Escolha um assunto ---')),
    (_(u'Dúvida'), _(u'Dúvida')),
    (_(u'Elogio'), _(u'Elogio')),
    (_(u'SAC'), _(u'SAC')),
    (_(u'Informação'), _(u'Informação')),
    (_(u'Reclamação'), _(u'Reclamação')),
)


class ContactForm(forms.Form):
    name = forms.CharField(label=u'Nome',
                           widget=forms.TextInput(
                               attrs={'class': 'form-control',
                                      'placeholder': 'Nome'}))
    phone = forms.CharField(label=u'Fone',
                            widget=forms.TextInput(
                                attrs={'class': 'form-control',
                                       'placeholder': 'Fone'}))
    email = forms.EmailField(label=u'E-mail',
                             widget=forms.TextInput(
                                 attrs={'class': 'form-control',
                                        'placeholder': 'E-mail'}))
    subject = forms.ChoiceField(label=u'Assunto', choices=SUBJECT_CHOICES,
                                widget=forms.Select(
                                    attrs={'class': 'form-control',
                                           'placeholder': 'Assunto'}))
    # subject = forms.CharField(label=u'Assunto',
    #                           widget=forms.TextInput(
    #                               attrs={'class': 'form-control',
    #                                      'placeholder': 'Assunto'}))
    message = forms.CharField(label=u'Mensagem',
                              widget=forms.Textarea(
                                  attrs={'class': 'form-control', 'rows': 6,
                                         'placeholder': 'Mensagem'}))

    def send_mail(self):
        subject = u'Contato do site (%s)' % self.cleaned_data['name']
        context = {
            'name': self.cleaned_data['name'],
            'phone': self.cleaned_data['phone'],
            'email': self.cleaned_data['email'],
            'subject': self.cleaned_data['subject'],
            'message': self.cleaned_data['message'],
        }
        message = render_to_string('contact_mail.txt', context)
        message_html = render_to_string('contact_mail.html', context)
        msg = EmailMultiAlternatives(subject, message,
                                     'no-reply@esperancanordeste.com.br',
                                     # ['contato@rhape.com.br']
                                     ['kleberss@gmail.com'])

        msg.attach_alternative(message_html, 'text/html')
        msg.send()


class TimelineForm(forms.ModelForm):
    period = forms.DateField(
        label=u'Período',
        widget=MonthYearWidget(years=xrange(1980, now.year+1)))

    class Meta:
        model = Timeline

esperancanordeste/core/templates/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <!--<meta http-equiv="X-UA-Compatible" content="IE=edge">-->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Esperança Nordeste">
    <meta name="author" content="OW7">
    <link rel="shortcut icon" href="{{ STATIC_URL }}ico/favicon.ico">

    <title>{{ enterprise.name }} - {{ enterprise.phone1 }}{% block title %}{% endblock title %}</title>

    <!-- Owl Carousel Assets -->
    <link href="{{ STATIC_URL }}owl-carousel/owl.carousel.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}owl-carousel/owl.theme.css" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <!--<link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">-->

    <!-- Custom styles for this template -->
    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

    <!-- Resources -->
    <link href="{{ STATIC_URL }}fonts/font-awesome-4.0.3/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/animate.css" rel="stylesheet">
    <link href="{{ STATIC_URL }}css/lightbox.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Ubuntu:300,400,500,700' rel='stylesheet' type='text/css'>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block extra_css %}

    {% endblock extra_css %}
  </head>

  <body>

    <!-- Navigation -->
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="top-new">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
              <img src="{{ STATIC_URL }}img/logo.png" alt="{{ enterprise.name }}">
            </a>
          </div>
          <!-- Collapse -->
          <div class="collapse navbar-collapse">
            <div class="row top-menu">
              <div class="col-md-8 pull-right">
                <ul class="nav navbar-nav navbar-right">
                  <li class="hidden-sm{% block nav_institutional %}{% endblock %}">
                    <a href="{% url 'institutional' %}">Institucional</a>
                  </li>
                  <!--
                  <li class="hidden-sm{% block nav_sale %}{% endblock %}">
                    <a href="{% url 'sale:home' %}">Área de Atuação</a>
                  </li>
                  -->
                  <li class="hidden-sm{% block nav_campain %}{% endblock %}">
                    <a href="{% url 'campain:home' %}">Campanhas</a>
                  </li>
                  <li class="hidden-sm{% block nav_estimate %}{% endblock %}">
                    <a href="{% url 'sale:home' %}">Cotação</a>
                  </li>
                  <li class="hidden-sm{% block nav_contact %}{% endblock %}">
                    <a href="{% url 'contact' %}">Contato</a>
                  </li>
                </ul>
                <div class="row info">
                  <div class="col-md-9 pull-right">
                    <div class="col-md-5 phone">{{ enterprise.phone1 }}</div>
                    <div class="col-md-5 atendimento">
                      SEGUNDA A SEXTA: 08H ÀS 18H
                      <!--<br>SABÁDO: 08H ÀS 12H-->
                    </div>
                    <div class="col-md-2 social">
                      <a href="https://www.facebook.com/pages/ESPERAN%C3%87A-NORDESTE-LTDA/214415315269900" target="_blank">
                        <img src="{{ STATIC_URL }}img/facebook_en.png">
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div><!--/.nav-collapse -->
        </div>
      </div>
      <div class="collapse navbar-collapse">
        <div class="container menu-two">
          <ul class="nav navbar-nav col-sm-9">
            <li class="dropdown">
              <a href="#" class="hidden-sm dropdown-toggle{% block nav_category %}{% endblock %}" data-toggle="dropdown">Categoria de Produtos <b class="caret"></b></a>
              <ul class="dropdown-menu">
                {% for cat in cat_list %}
                  <li>
                    <ul>
                      <li class="col-sm-3">
                        <a href="{% url 'catalog:category_list' cat.slug %}">{{ cat.name }}</a>
                      </li>
                    </ul>
                  </li>
                {% endfor %}
              </ul>
            </li>
            <li class="hidden-sm{% block nav_brand %}{% endblock %}">
              <a href="{% url 'brand' %}">Marcas</a>
            </li>
            <li class="hidden-sm{% block nav_promotion %}{% endblock %}">
              <a href="{% url 'campain:cat_list' 'promocao' %}">Promoções</a>
            </li>
            <li class="hidden-sm{% block nav_catalog %}{% endblock %}">
              <a href="{% url 'catalog:home' %}">Catálogo de Produtos</a>
            </li>
          </ul>
          <div class="col-sm-3 search">
            <!-- Search -->
            <form role="form" action="/catalogo/" method="get">
                <div class="row">
                    <div class="input-group">
                      <input id="search" name="search" type="text" class="form-control" placeholder="Buscar Produto...">
                      <span class="input-group-btn">
                        <button class="btn" type="submit"><i class="fa fa-search"></i></button>
                      </span>
                    </div><!-- /.input-group -->
                </div><!-- /.row -->
              </div>
            </form>
          </div>
        </div>
        <div class="container shadow"><br></div>
      </div>
    </div> <!-- / .navigation -->

    {% block content %}

    {% endblock content %}

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <!-- Contact Us -->
          <div class="col-sm-3">
            <h4><i class="fa fa-map-marker"></i> Contato</h4>
            <p>Não hesite em contactar-nos se você tiver dúvidas ou solicitações:</p>
            <p>
              {{ enterprise.address }}, {{ enterprise.number }}<br>
              CEP {{ enterprise.cep }}, {{ enterprise.district }}, {{ enterprise.city }}/{{ enterprise.state }}<br>
              Fone: {{ enterprise.phone1 }}<br>
              Email: {{ enterprise.email }}
            </p>
          </div>

          <!-- Recent Tweets -->
          <div class="col-sm-4 social">
            <h4><i class="fa fa-users"></i> Social</h4>
            {% for logo in social_list %}
                {% if forloop.first %}
                    <p>{{ logo.social }}</p>
                {% endif %}
                <div class="col-sm-6">
                  <img class="img-responsive" src="{{ logo.image.url }}" alt="{{ logo.name }}">
                </div>
            {% endfor %}
          </div>

          <!-- Newsletter -->
          <div class="col-sm-3">
            <h4><i class="fa fa-envelope"></i> Newsletter</h4>
            <p>
              Digite seu e-mail abaixo para assinar nossa newsletter gratuita.
              <br>
              Prometemos não incomodá-lo muitas vezes!
            </p>

            {% if subscribe_success %}
              <p>Obrigado!<br>Email cadastrado com sucesso.</p>
              <a href="{% url 'home' %}" class="btn btn-blue">Voltar</a>
            {% elif subscribe_exist %}
              <p>Esse email já está cadastrado.</p>
              <a href="{% url 'home' %}" class="btn btn-blue">Voltar</a>
            {% else %}
            <form method="post" action=".">
              {% csrf_token %}
              <div class="row">
                <div class="col-sm-11">
                {% csrf_token %}
                {% for field in newsletter_form %}
                  <div class="input-group">
                    <label class="sr-only" for="{{ field.name }}">{{ field.label }}</label>
                    {{ field }}
                    <input type="hidden" name="subscribe" value="subscribe">
                    <span class="input-group-btn">
                      <input name="Subscribe" type="submit" name="enviar" class="btn btn-default" value="OK">
                    </span>
                  </div>
                  {{ field.errors }}
                {% endfor %}
                </div>
              </div>
            </form>
            {% endif %}
          </div>

          <div class="col-sm-2 iso">
            <h4><i class="fa fa-users"></i> ISO 9001</h4>
            <img class="img-responsive" src="{{ STATIC_URL }}img/iso-9001.jpg" alt="ISO 9001" title="ISO 9001">
          </div>

        </div>
      </div>
    </footer>

    <!-- Copyright -->
    <div class="bot">
        <div class="container">
          <div class="row">
            <div class="col-sm-10">
              <div class="copyright">
                Copyright 2014 - {{ enterprise.name }} - CNPJ: {{ enterprise.cnpj }}
              </div>
            </div>
            <div class="col-sm-2 pull-right">
              <div class="copyright pull-right">
                <a href="http://www.jookle.com.br/">Jookle</a>
              </div>
            </div>
          </div>  <!-- / .row -->
        </div> <!-- / .container -->
    </div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
    <script src="{{ STATIC_URL }}js/scrolltopcontrol.js"></script>
    <script src="{{ STATIC_URL }}js/lightbox-2.6.min.js"></script>
    <script src="{{ STATIC_URL }}js/custom.js"></script>
    <script src="{{ STATIC_URL }}js/index.js"></script>
    <script src="{{ STATIC_URL }}owl-carousel/owl.carousel.js"></script>

    <script>
      $(document).ready(function() {
        $("#owl-demo").owlCarousel({
          autoPlay: 5000,
          stopOnHouver: true,
          navigation: false,
          paginationSpeed: 1000,
          goToFirstSpeed: 0,
          singleItem: true,
          autoHeight: true,
          //transitionStyle: "fade"
        });
        $("#owl-demo2").owlCarousel({
          autoPlay: 5000,
          stopOnHouver: true,
          navigation: false,
          paginationSpeed: 1000,
          goToFirstSpeed: 0,
          singleItem: true,
          autoHeight: false,
          //transitionStyle: "fade"
        });
        $("#owl-suppliers").owlCarousel({
          autoPlay: 3000,
          items: 11,
          /*itemsDesktop : [1199,3],
          itemsDesktopSmall : [979,3]*/
          itemsDesktop : [1199,8], //5 items between 1000px and 901px
          itemsDesktopSmall : [979,6], // betweem 900px and 601px
          itemsTablet: [600,4], //2 items between 600 and 0
          itemsMobile : false, // itemsMobile disabled - inherit from itemsTablet option
          navigation: false,
          pagination: false,
        });
      });
    </script>

    <script>
      $(document).ready(function(){
          $("input[type=email]").addClass("form-control");
      });
    </script>

    {% block extra_js %}

    {% endblock extra_js %}
  </body>
</html>

esperancanordeste/core/templates/order.html
{% extends "base.html" %}

{% block nav_order %} active{% endblock %}

{% block content %}

    <!-- Wrapper -->
    <div class="wrapper">

      <!-- Topic Header -->
      <div class="topic order">
        <div class="container">
          <div class="row">
            <div class="col-sm-12">
              <h3>Receba seu Pedido</h3>
            </div>
            <!--
            <div class="col-sm-8">
              <ol class="breadcrumb pull-right hidden-xs">
                <li><a href="index.html">Home</a></li>
                <li class="active">Contact Us</li>
              </ol>
            </div>
            -->
          </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col-sm-12">
            <h3 class="headline first-child">
              <span>Instruções para recebimento do seu pedido</span>
            </h3>
            {% for o in order_list %}
              {% autoescape off %}
              <p>{{ o.body|linebreaks|cut:"../../../.." }}</p>
              {% endautoescape %}
            {% endfor %}
          </div>
        </div> <!-- / .row -->
      </div> <!-- / .container -->

    </div> <!-- / .wrapper -->

{% endblock content %}